const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,SESSION_TTL=Number(process.env.SESSION_TTL_MS||1000*60*60*24*7);
const ALLOWED_ORIGIN=String(process.env.ALLOWED_ORIGIN||'').trim().replace(/\/$/,'');
const AUTH_SECRET=String(process.env.AUTH_SECRET||'').trim()||crypto.randomBytes(32).toString('hex');
const ADMIN_EMAILS=new Set(String(process.env.ADMIN_EMAILS||process.env.ADMIN_EMAIL||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean));const AI_RATE_WINDOW=60000,AI_RATE_MAX=Number(process.env.AI_RATE_MAX||30);const rate=new Map();
const users=new Map(),sessions=new Map(),DB_FILE=path.join(ROOT,'juriscope-data.json');let db={users:{},profiles:{},leaderboard:[]};
try{if(fs.existsSync(DB_FILE))db={...db,...JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}}catch(e){};function persist(){try{fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}catch(e){}}
function hashLegacy(p){return crypto.createHash('sha256').update(String(p)).digest('hex')}
function hashPassword(p){return crypto.scryptSync(String(p),crypto.randomBytes(16),32).toString('hex')}
function verifyPassword(p,stored){if(String(stored).startsWith('s2$')){const [,salt,hash]=String(stored).split('$');try{const got=crypto.scryptSync(String(p),Buffer.from(salt,'hex'),32).toString('hex');return crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(hash,'hex'))}catch(e){return false}}return stored===hashLegacy(p)}
function secureHash(p){const salt=crypto.randomBytes(16).toString('hex');return `s2$${salt}$${crypto.scryptSync(String(p),Buffer.from(salt,'hex'),32).toString('hex')}`}
function b64(v){return Buffer.from(v).toString('base64url')}
function signToken(user){const payload={u:user,exp:Date.now()+SESSION_TTL};const raw=b64(JSON.stringify(payload));const sig=crypto.createHmac('sha256',AUTH_SECRET).update(raw).digest('base64url');return raw+'.'+sig}
function verifyToken(t){try{const [raw,sig]=String(t||'').split('.');if(!raw||!sig)return null;const expected=crypto.createHmac('sha256',AUTH_SECRET).update(raw).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const p=JSON.parse(Buffer.from(raw,'base64url').toString('utf8'));if(!p?.u||Number(p.exp)<Date.now())return null;return withRole(p.u)}catch(e){return null}}
function isAdminEmail(email){return ADMIN_EMAILS.has(String(email||'').trim().toLowerCase())}function withRole(user){return user?{...user,role:isAdminEmail(user.email)?'admin':'user'}:user}function authUser(req){const h=String(req.headers.authorization||'');const t=h.startsWith('Bearer ')?h.slice(7):'';return verifyToken(t)}function requireAdmin(req){const u=authUser(req);return u&&u.role==='admin'?u:null}
function profileFor(u){if(!u)return null;if(!db.profiles[u.id])db.profiles[u.id]={study:null,gamification:null,favorites:[],aiHistory:[],updatedAt:null};return db.profiles[u.id]}
for(const [email,rec] of Object.entries(db.users||{}))users.set(email,rec);
function headers(origin='',secure=false){const h={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(),microphone=(),geolocation=()','Cross-Origin-Resource-Policy':'same-origin','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'};if(ALLOWED_ORIGIN&&origin===ALLOWED_ORIGIN)h['Access-Control-Allow-Origin']=ALLOWED_ORIGIN;if(secure)h['Strict-Transport-Security']='max-age=31536000; includeSubDomains';return h}
function json(res,status,body,origin,secure=false){res.writeHead(status,headers(origin,secure));res.end(JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let s='',n=0;req.on('data',c=>{n+=c.length;if(n>1024*1024){reject(new Error('Request too large'));req.destroy()}else s+=c});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})})}
function limited(ip){const now=Date.now(),r=rate.get(ip)||{start:now,count:0};if(now-r.start>AI_RATE_WINDOW){r.start=now;r.count=0}r.count++;rate.set(ip,r);return r.count>AI_RATE_MAX}
async function ai(message,context){const url=process.env.AI_API_URL,key=process.env.AI_API_KEY,model=process.env.AI_MODEL;if(!url||!key||!model){const c=context||{},title=c.title||'this case',facts=c.facts||'No case facts were supplied in the archive context.',question=c.question||'No legal question was supplied in the archive context.',decision=c.decision||'No decision was supplied in the archive context.',why=c.why||'No reasoning summary was supplied in the archive context.',theme=c.theme||c.themes||'No doctrine/theme was supplied.',m=String(message||'').toLowerCase();let answer;if(m.includes('5-year')||m.includes('5 year')||m.includes('simple'))answer=`${title}, very simply: ${facts}\n\nThe legal question was: ${question}\n\nThe court decided: ${decision}`;else if(m.includes('why')||m.includes('decision'))answer=`Why the decision in ${title}:\n\n${decision}\n\nReasoning in the archive: ${why}`;else if(m.includes('counterargument'))answer=`A useful counterargument to test is whether the court's stated rule should apply differently to the facts.\n\nCase context: ${facts}\n\nLegal question: ${question}`;else if(m.includes('doctrine')||m.includes('principle'))answer=`Key doctrine for ${title}: ${theme}\n\nRemember the distinction between the legal rule, its application to the facts, and the court's final outcome.`;else if(m.includes('compare'))answer=`For comparison, focus on cases involving the same legal theme (${theme}), then compare facts, legal question, court, reasoning, and outcome.`;else answer=`${title}\n\nFacts: ${facts}\n\nLegal question: ${question}\n\nDecision: ${decision}\n\nWhy it matters: ${why}\n\nKey theme: ${theme}`;return {answer,demo:true}}
const system=`You are Juriscope AI, an educational legal-study assistant. Use only the supplied Juriscope archive context for case-specific claims. Distinguish court decisions from explanation and do not present educational information as legal advice. Context: ${JSON.stringify(context||{})}`;
const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model,input:[{role:'system',content:system},{role:'user',content:String(message||'')}]} )});if(!r.ok)throw new Error(`AI provider returned ${r.status}`);const d=await r.json();return {answer:d.output_text||d.answer||d.choices?.[0]?.message?.content||'The AI provider returned no readable answer.'}}
const server=http.createServer(async(req,res)=>{const origin=String(req.headers.origin||'');const secure=String(req.headers['x-forwarded-proto']||'').split(',')[0].trim().toLowerCase()==='https';if(req.method==='OPTIONS'){res.writeHead(204,headers(origin,secure));return res.end()}try{const ip=String(req.headers['x-real-ip']||req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',').pop().trim();
if(req.method==='POST'&&req.url==='/api/auth/register'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return json(res,400,{error:'Use a valid email and a password of at least 8 characters.'},origin);if(users.has(email))return json(res,409,{error:'Account already exists.'},origin);const user=withRole({id:crypto.randomUUID(),name:String(b.name||'Juriscope Student').trim().slice(0,80),email});const rec={user:{id:user.id,name:user.name,email:user.email},password:secureHash(password)};users.set(email,rec);db.users[email]=rec;persist();const t=signToken(user);return json(res,200,{user,token:t},origin,secure)}
if(req.method==='POST'&&req.url==='/api/auth/login'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),u=users.get(email);if(!u||!verifyPassword(b.password,u.password))return json(res,401,{error:'Invalid credentials.'},origin);if(!String(u.password).startsWith('s2$')){u.password=secureHash(b.password);db.users[email]=u;persist()}const loggedUser=withRole(u.user);const t=signToken(loggedUser);return json(res,200,{user:loggedUser,token:t},origin,secure)}
if(req.method==='POST'&&req.url==='/api/sync'){const u=authUser(req);if(!u)return json(res,401,{error:'Authentication required.'},origin);const b=await body(req),p=profileFor(u);p.study=b.study||p.study;p.gamification=b.gamification||p.gamification;p.favorites=Array.isArray(b.favorites)?b.favorites:p.favorites;p.aiHistory=Array.isArray(b.aiHistory)?b.aiHistory.slice(0,50):p.aiHistory;p.updatedAt=new Date().toISOString();persist();return json(res,200,{ok:true,profile:p},origin)}
if(req.method==='GET'&&req.url==='/api/sync'){const u=authUser(req);if(!u)return json(res,401,{error:'Authentication required.'},origin);return json(res,200,{profile:profileFor(u)},origin)}
if(req.method==='POST'&&req.url==='/api/leaderboard'){const u=authUser(req);if(!u)return json(res,401,{error:'Authentication required.'},origin);const b=await body(req),xp=Math.max(0,Number(b.xp||0)),sessionsN=Math.max(0,Number(b.sessions||0)),arr=Array.isArray(db.leaderboard)?db.leaderboard:[],row={id:u.id,name:u.name||'Juriscope Student',xp,sessions:sessionsN,updatedAt:new Date().toISOString()},i=arr.findIndex(x=>x.id===u.id);if(i>=0)arr[i]=row;else arr.push(row);db.leaderboard=arr;persist();return json(res,200,{ok:true},origin)}

if(req.method==='GET'&&req.url==='/api/admin/me'){const u=requireAdmin(req);if(!u)return json(res,403,{error:'Admin access required.'},origin);return json(res,200,{user:u,stats:{users:Object.keys(db.users||{}).length,profiles:Object.keys(db.profiles||{}).length,leaderboard:(db.leaderboard||[]).length}},origin)}
if(req.method==='GET'&&req.url==='/api/admin/users'){const u=requireAdmin(req);if(!u)return json(res,403,{error:'Admin access required.'},origin);const list=Object.values(db.users||{}).map(r=>({id:r.user?.id,name:r.user?.name,email:r.user?.email,role:isAdminEmail(r.user?.email)?'admin':'user'}));return json(res,200,{users:list},origin)}
if(req.method==='GET'&&req.url==='/api/admin/leaderboard'){const u=requireAdmin(req);if(!u)return json(res,403,{error:'Admin access required.'},origin);return json(res,200,{leaderboard:(db.leaderboard||[]).slice().sort((a,b)=>Number(b.xp)-Number(a.xp))},origin)}
if(req.method==='GET'&&req.url==='/api/leaderboard')return json(res,200,{leaderboard:(db.leaderboard||[]).slice().sort((a,b)=>Number(b.xp)-Number(a.xp)).slice(0,10)},origin)
if(req.method==='POST'&&req.url==='/api/ai'){if(limited(ip))return json(res,429,{error:'Too many AI requests. Please try again shortly.'},origin);const b=await body(req);return json(res,200,await ai(b.message,b.context),origin)}
let file=req.url==='/'?'/index.html':req.url.split('?')[0];const full=path.resolve(ROOT,'.'+file);if(!full.startsWith(path.resolve(ROOT)+path.sep)||!fs.existsSync(full)||!fs.statSync(full).isFile())return json(res,404,{error:'Not found'},origin);const ext=path.extname(full),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Cache-Control':ext==='.html'?'no-cache':'public, max-age=86400'});fs.createReadStream(full).pipe(res)}catch(e){console.error(e);json(res,500,{error:'Server error'},origin)}});
server.listen(PORT,()=>console.log(`Juriscope running at http://localhost:${PORT}`));
